### ISSUE TITLE
IOS issues

### ISSUE THREAD

**Issue by benedictchuajj** [benedictchuajj/Orbital2021#59]
Currently, the app is not optimised for IOS users as there are some components and screens that IOS users are unable to easily navigate around or doesn't look good on IOS (but looks good on Android and vice versa).

This list will be updated as more user testing is done for IOS. Feel free to add comments to this so I can collate them into the list. [ Last updated: 08/06/21 ]

Major issues:
- When adding post, after adding image to the post and typing text into the text input field, keyboard ends up obstructing the submit button and since there is no back button to remove keyboard like in Android, user is essentially trapped in the app and has to reload. For IOS with bigger screens, button is only partially obstructed and user can still navigate.

Minor issues:
- Styling with Alert is different for IOS and Android. Currently, styling is optimised for Android as options are from left to right (Cancel, Delete, Edit) but for IOS it appears top down and thus looks weird from a user's perspective.

**Comment by luayida99** [comment]
On iOS, clicking into a forum post and trying to comment when there are more than 3 comments will cause the send bar to be hidden by the keyboard, thus the user is unable to publish the comment.

**Comment by luayida99** [comment]
> On iOS, clicking into a forum post and trying to comment when there are more than 3 comments will cause the send bar to be hidden by the keyboard, thus the user is unable to publish the comment.

This has been fixed with #71

**Comment by luayida99** [comment]
> Currently, the app is not optimised for IOS users as there are some components and screens that IOS users are unable to easily navigate around or doesn't look good on IOS (but looks good on Android and vice versa).
> 
> This list will be updated as more user testing is done for IOS. Feel free to add comments to this so I can collate them into the list. [ Last updated: 08/06/21 ]
> 
> Major issues:
> 
> * When adding post, after adding image to the post and typing text into the text input field, keyboard ends up obstructing the submit button and since there is no back button to remove keyboard like in Android, user is essentially trapped in the app and has to reload. For IOS with bigger screens, button is only partially obstructed and user can still navigate.
> 
> Minor issues:
> 
> * Styling with Alert is different for IOS and Android. Currently, styling is optimised for Android as options are from left to right (Cancel, Delete, Edit) but for IOS it appears top down and thus looks weird from a user's perspective.

Both issues have been resolved with #71 and #74
