### ISSUE TITLE
Friends page bottom covered by taskbar

### ISSUE THREAD

**Issue by luayida99** [benedictchuajj/Orbital2021#8]

**Comment by benedictchuajj** [comment]
Same problem as #9 and possibly affects all main pages.

Possible fixes that could be explored: 
-Hide BottomNavi bar when scrolling down and make it reappear when swiping up. **allows more content to be displayed**
-set MarginBottom for all main pages

**Comment by luayida99** [comment]
> Same problem as #9 and possibly affects all main pages.
> 
> Possible fixes that could be explored:
> -Hide BottomNavi bar when scrolling down and make it reappear when swiping up. **allows more content to be displayed**
> -set MarginBottom for all main pages

Current fix for FriendsScreen wraps the affected component in a view that is then styled to fit the screen. Agree that hiding bar might be worth exploring
